name: dontcallmejames
favicon: null
layout_spectrum: 0.7617663021665066
typography_spectrum: 0.9100310034118593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#930505'
    - '#bdbdbd'
    - '#000000'
    - '#ffffff'
    - '#926363'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
